### PR TITLE
Synced main with APL main branch

### PR DESCRIPTION
**Pull request by myersja**
Syncing changes with APL main branch to capture changes since submitting the open source request.

### CODE REVIEW

**Comment by ctubbsii** [comment]
@myersja Is it okay if I merge both this and #2 into their respective branches? I would like to squash them in, but in a particular way, so the commits look like:

```
  commit from PR #2 (squashed) - HEAD of develop
    |
  commit from PR #1 (squashed) - HEAD of main
    |
  current HEAD of develop/main
```

Because the squash and merge button will rewrite the commit known as db5ba3c1f88f81f821658020f53425b205674c59, which is common to both PRs, GitHub can very easily mess this up if not done in a particular way, resulting in a somewhat messier git history, which I'd like to avoid as this project gets its footing as an open source project.

**Review by stephensmalley — COMMENTED** [review]
It appears that this commit adds a number of files but makes no other changes. I am unclear on the connection between these new files and the existing content, if any. Can you clarify?

**Comment by myersja** [comment]
Stephen,

The contrib directory contains demonstration code. The addition in this PR includes a demo of IoTA running on ARM TrustZone, which integrates with Maat to demonstrate measurement of a running IoT-style microcontroller.

The other additions are in the m4 directory and are used by autotools for building. I'm actually unsure how these deviated between the code we gave the agency and our current codebase, as the relevant commit message suggests they were added for the open source release. As the goal was to sync our APL internal repo with the public open-source repo, I thought it best to include them.

Other than that, not much has changed on the main branch. As previously mentioned, our improvements go into the develop branch until we are ready to cut a release, which will happen once the TPM2 code has passed testing and review.

**Review by stephensmalley — APPROVED** [review]

**Comment by stephensmalley** [comment]
Assuming that @ctubbsii will merge these as he suggested above. If not, let me know.

**Comment by ctubbsii** [comment]
> Assuming that @ctubbsii will merge these as he suggested above. If not, let me know.

Both PRs could also be merged from the command-line, as fast-forward merges to their respective branches. Then, GitHub won't rewrite the commit and there won't be anything for me to help with. It's up to you.

**Pull request merged**
